### ISSUE TITLE
Any plans to update libv8

### ISSUE THREAD

**Issue by joehoyle** [AlexMasterov/dockerfiles#12]
Hey there,

Thanks so much for sharing these docker files. I was wondering if you plan to release new builds for the latest version of V8?

Also, I noticed you have libv8 7.3+ in this repo, but there are no docker images published for them, any plans to push that?

Thanks!

**Comment by AlexMasterov** [comment]
Hello!
Thank you for your interest. Sorry for so late reply, life was too busy.

I added a new Dockerfile, you can try it:
```sh
docker build --build-arg V8_VERSION=9.1.261 -t v8 github.com/AlexMasterov/dockerfiles.git#:alpine-v8
```
> V8_VERSION >= 6.1.211

See also the README with [mini-FAQ](https://github.com/AlexMasterov/dockerfiles#alpine-v8).

**Comment by Manouchehri** [comment]
Would it be possible to build V8 with [musl-cross-make](https://github.com/richfelker/musl-cross-make)?

**Comment by AlexMasterov** [comment]
> Would it be possible to build V8 with [musl-cross-make](https://github.com/richfelker/musl-cross-make)?

I know about these [toolchains](https://musl.cc/). I will try to use them as I have free time. Thank you 👍🏻
