### ISSUE TITLE
How is GN compiled for musl?

### ISSUE THREAD

**Issue by hgl** [AlexMasterov/dockerfiles#5]
In alpine-libv8, gn is downloaded from dropbox. Is it possible to build it directly in Dockerfile? Or could you share the script that built it?

Thanks.

**Comment by AlexMasterov** [comment]
Sorry for the delay.

> How is GN compiled for musl?

[It's a long, boring story.](https://github.com/phpv8/v8js/issues/275) Ideally, `gn` and `v8` should be a Alpine package.

> Is it possible to build it directly in Dockerfile? Or could you share the script that built it?

Yes, but then Dockerfile will look a bit verbose. You can see an example [here](https://github.com/AlexMasterov/dockerfiles/blob/912ffd01c5a848045b7235fc326275424512e095/alpine-v8-lib/Dockerfile#L26-L48) (this includes [patches](https://github.com/AlexMasterov/dockerfiles/tree/912ffd01c5a848045b7235fc326275424512e095/alpine-v8-lib/patch)).

**Comment by hgl** [comment]
Thanks for the heads up. It's indeed quite challenging. Appreciate the work you did on that.

I haven't looked too deeply into how nodejs is built on alpine, but I wonder if that could be leveraged to build libv8 for musl? After all, it contains v8.

**Comment by AlexMasterov** [comment]
It seems that they still use GYP to build V8.

Node.js already built in Docker containers, it just downloaded.
