### ISSUE TITLE
alpinelibv8 build failing

### ISSUE THREAD

**Issue by alexsaar** [AlexMasterov/dockerfiles#8]
Tried to build https://github.com/AlexMasterov/dockerfiles/tree/master/alpine-libv8 with following command: `docker build --build-arg V8_VERSION=6.3.53 --build-arg V8_DIR=/usr/local/v8 .`

But it resulted in the error below. Any advice? Couldn't find any solution so far. My best guess is that some dependencies for .cipd_client are not satisfied.

My I'm using Docker version 17.06.2-ce-mac27

OK: 320 MiB in 78 packages
Cloning into '/tmp/depot_tools'...
Running: gclient config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "managed": False,
    "name": "v8",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
/tmp/depot_tools/cipd: line 88: /tmp/depot_tools/.cipd_client: No such file or directory
selfupdate failed: run `CIPD_HTTP_USER_AGENT_PREFIX=depot_tools/509776ebbbef259a459a32235dac53998c5c12b8/manual /tmp/depot_tools/.cipd_client selfupdate -version 'git_revision:cf5b0de14e94b06274d15e84b19449f580576e80'` to diagnose

/tmp/depot_tools/cipd: line 94: /tmp/depot_tools/.cipd_client: No such file or directory
/tmp/depot_tools/cipd: line 88: /tmp/depot_tools/.cipd_client: No such file or directory
selfupdate failed: run `CIPD_HTTP_USER_AGENT_PREFIX=depot_tools/509776ebbbef259a459a32235dac53998c5c12b8/manual /tmp/depot_tools/.cipd_client selfupdate -version 'git_revision:cf5b0de14e94b06274d15e84b19449f580576e80'` to diagnose

/tmp/depot_tools/cipd: line 94: /tmp/depot_tools/.cipd_client: No such file or directory
Error: Command 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' returned non-zero exit status 1 in /tmp
'
Running: gclient sync --no-history --with_branch_heads
Traceback (most recent call last):
  File "/tmp/depot_tools/fetch.py", line 299, in <module>
    sys.exit(main())
  File "/tmp/depot_tools/fetch.py", line 294, in main
    return run(options, spec, root)
  File "/tmp/depot_tools/fetch.py", line 288, in run
    return checkout.init()
  File "/tmp/depot_tools/fetch.py", line 131, in init
    self.run_gclient(*sync_cmd)
  File "/tmp/depot_tools/fetch.py", line 78, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "/tmp/depot_tools/fetch.py", line 68, in run
    return subprocess.check_output(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('gclient', 'sync', '--no-history', '--with_branch_heads')' returned non-zero exit status 2
The command '/bin/sh -c apk add --update --virtual .v8-build-dependencies     bash     binutils-gold     ca-certificates     curl     g++     gcc     git     glib-dev     icu-dev     linux-headers     make     ninja     python     tar     wget     xz   && DEPOT_TOOLS_DIR="/tmp/depot_tools"   && DEPOT_TOOLS_GIT="https://chromium.googlesource.com/chromium/tools/depot_tools.git"   && git clone --depth 1 ${DEPOT_TOOLS_GIT} ${DEPOT_TOOLS_DIR}   && export PATH="${PATH}:${DEPOT_TOOLS_DIR}"   && cd /tmp   && fetch     --force     --no-history       v8   && cd /tmp/v8   && gclient sync     -r ${V8_VERSION}     -j $(getconf _NPROCESSORS_ONLN)   && apk add --virtual .gn-runtime-dependencies     libevent     libexecinfo     libstdc++   && wget -O - ${GN_SOURCE} | tar xz -C /tmp/v8/buildtools/linux64/   && ./tools/dev/v8gen.py     x64.release     --       binutils_path=\"/usr/bin\"       target_os=\"linux\"       target_cpu=\"x64\"       v8_target_cpu=\"x64\"       v8_use_external_startup_data=false       v8_enable_future=true       is_official_build=true       is_component_build=true       is_clang=false       is_debug=false       use_custom_libcxx=false       use_sysroot=false       use_gold=false       use_allocator=\"tcmalloc\"       use_allocator_shim=false       enable_nacl=false       treat_warnings_as_errors=false       symbol_level=0   && ninja -C out.gn/x64.release/ d8   && mkdir -p ${V8_DIR}/include ${V8_DIR}/lib   && cp -R /tmp/v8/include/* ${V8_DIR}/include/   && (cd /tmp/v8/out.gn/x64.release;       cp lib*.so icudtl.dat ${V8_DIR}/lib/)   && apk del .v8-build-dependencies .gn-runtime-dependencies   && rm -rf /var/cache/apk/* /var/tmp/* /tmp/*' returned a non-zero code: 1

**Comment by rombert** [comment]
Same here, using

```
$ docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:57:21 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:19 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by AlexMasterov** [comment]
Fixed.

**Comment by alexsaar** [comment]
thanks, works for me as well now.
